name = "Aline"
uuid = "01e4e282-a1b7-4c2d-880e-63c63ef1610f"
version = "0.0.1"
authors = ["AlineVissuzaine <aline.vissuzaine@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
julia = "1.10"
